In [ ]:
#numpy are ndarrays jo ke bna hua C me lakin chale python me
import numpy as np

Creation of numpy arrays

In [ ]:
#1D
one_d=np.array([1,2,3,4,5])
print(one_d)
print(type(one_d))
#2D
two_d=np.array([[1,2],[3,4]])
print(two_d)
#3D(tensor)
three_D=np.array([[[1,2],[3,4]]])
print(three_D)
#using arange
in_range=np.arange(1,10,2)
print(in_range)
#using arange and reshape together .reshape(rows, columns)
#dono number ka product should be equal to number of items in matrix
in_range=np.arange(1,12,2).reshape(2,3)
print(in_range)
#dtype
float_array=np.array([1,2,3,4,5], dtype=float )
print(float_array)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
[1 3 5 7 9]
[[ 1  3  5]
 [ 7  9 11]]
[1. 2. 3. 4. 5.]


In [ ]:
#utility functions for initialising the value especially in  neural networks
#zeros
zero_arrays=np.zeros((3,4)) #np.zeros(4) columns
print(zero_arrays)
#ones
ones_arrays=np.ones((3,4))
print(ones_arrays)
#random
random_array=np.random.random((3,4))
print(random_array)
#linspace
linspace=np.linspace(1,100,10) #(lower, upper,no_of_items) given range me equal distance pr points arrange krta ha
print(ones_arrays)
#identity
identity=np.identity(3)
print(identity)
#replaced of identity
eye=np.eye(3)
print(eye)
#empty np.empty((rows=2,col=3))
empty=np.empty((2,3))
print(empty)
#full with specific number
full=np.full((3,4),7)
print(full)
#log space start=10^1, stop=10^3, no of elements=4
log_space=np.logspace(1,3,4)
print(log_space)
#diagnal
diagnol=np.diag([1,2,3])
print(diagnol)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.76152626 0.57299169 0.47601665 0.42023809]
 [0.19920931 0.37227283 0.22795451 0.24592574]
 [0.22202487 0.12830307 0.33801309 0.75103378]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3.33772792e-307 4.22786102e-307 2.78145267e-307]
 [4.00537061e-307 2.23419104e-317 0.00000000e+000]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[  10.           46.41588834  215.443469   1000.        ]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


Changing Datatypes


In [ ]:
a=np.array([1,2,3,4,5])
a.astype(np.int64)

array([1, 2, 3])

Arrays Functions

In [57]:
#trignometric functions
#numpy epects radians so if you want to use this concert to radians
angles = np.array([0,30,45,60])
a = np.deg2rad(angles)
np.sin(a)
np.cos(a)
np.tan(a)


array([0.        , 0.57735027, 1.        , 1.73205081])

In [59]:
#dot product
#a=(3,4), b=(4,3) j of first and i of second then only possible resultant i of A,j of B
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])