In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
c=b=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])

In [3]:
#Shape
print("shape: ",b.shape) #structure of the array (rows, columns, depth etc.), shape no of elements in each dimension like 1 3d array contain 2D array and each 2D array has 2 rows and 2 columns

#Size
print("size: ",a.size) #print the total no of elements

#itemsize
print("itemsize->no of elements: ",a.itemsize) #how many bytes an item occupy in memory

#dtype
print("datatype->dtype:",a.dtype) #data type of elements

#ndim
print("dimensions->ndim: ",a.ndim) #tell how many dimensions array has 1D,...

#Converting multidimension into 1D
#View
d=np.ravel(b) #convert n dimensional array into 1D array 
print("ravel(view)->multidim to 1D: ", d) #returns the view changes the original
#Copy
e=c.flatten()#changes n dimensional array into 1D array 
print("flatten(copy)->multidim to 1D: ",e) #returs the copy

#Transpose
transpose= a.T # reverses the order of axes.
print("transpose(rows into col and col into rows): \n",transpose)
array=[[1,2],[3,4]] 

#Swapaxes
swapaxes=np.swapaxes(array, 0, 1) #0->col wise 1->row wise #(1,3)(2,4) 
print(swapaxes) # swaps only the two axes you specify.

#Squeeze
a = np.array([[[1,2,3]]])
print("Before squeeze: ",a.shape)
y=np.squeeze(a, axis=1)
print(y) # remove dimensions of size 1
print("Squeeze with specific axis: ",y.shape) #(1,1,3)
x = np.squeeze(a, axis=None)
print("Squeeze without a specific axis", x.shape) #remove the extra dimensions (3,)

#expanddims
a=np.array([1,2,3,4])
b = np.expand_dims(a, axis=0) #axis 0 ha means jo original ha wo column bne ga so (1,4)
print(b)
print(b.shape)
c=np.expand_dims(a, axis=1)
print(c)
print(c.shape)

#htsack (for horizontal joining the rows, joining arrays side by side)
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
c=np.hstack((a,b))
print(c)

#vstack ((for vertical joining the columns))
d=np.vstack((a,b))
print(d)

#dstack creates 3D array
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dstack((a,b))
print(c)

#np.concatinate
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b) , axis=0)
print(c)
#for using concatinate with axis 1 the array must be multidimensional
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b) , axis=0) #column wise
print(c)
c = np.concatenate((a,b) , axis=1) #row wise
print(c)

#np.hsplit (kis ko, kitne parts me)
e=np.hsplit(c, 2)
print(e)

#np.vsplit
f=np.hsplit(c, 2)
print(f)

#np.tile/ np.repeat
g=np.repeat(a,3) #repeat every element 
d=np.tile(a,3) #repeat the entire array
print(g)
print(d)

shape:  (2, 2, 2)
size:  5
itemsize->no of elements:  8
datatype->dtype: int64
dimensions->ndim:  1
ravel(view)->multidim to 1D:  [1 2 3 4 4 5 6 7]
flatten(copy)->multidim to 1D:  [1 2 3 4 4 5 6 7]
transpose(rows into col and col into rows): 
 [1 2 3 4 5]
[[1 3]
 [2 4]]
Before squeeze:  (1, 1, 3)
[[1 2 3]]
Squeeze with specific axis:  (1, 3)
Squeeze without a specific axis (3,)
[[1 2 3 4]]
(1, 4)
[[1]
 [2]
 [3]
 [4]]
(4, 1)
[1 2 3 4 5 5 6 7 8 9]
[[1 2 3 4 5]
 [5 6 7 8 9]]
[[[1 4]
  [2 5]
  [3 6]]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[1 1 1 2 2 2 3 3 3 4 4 4]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


When tile() is Useful in AI / ML

It is used when you need to:
duplicate datasets
expand patterns
match shapes for broadcasting
generate repeated features

#meshgrids
(len(y), len(x))
x->repeats across rows
y->across columns

In [5]:
x = np.arange(3)
y = np.arange(3)

X,Y = np.meshgrid(x,y)
print(X)
print(Y)
import numpy as np

x = np.array([1,2,3])      # length = 3
y = np.array([4,5])        # length = 2

X, Y = np.meshgrid(x, y)

print(X.shape)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]
(2, 3)
