In [2]:
import numpy as np
a = np.array([10,20,30,40,50,60,70,80,90,100])

One dimensional

In [ ]:
# Access the first element.
print(a[0])
# Access the last element using negative indexing.
print(a[-1])
# Extract elements from index 2 to 6.
print(a[2:6])
# Extract the first five elements.
print(a[:5])
# Extract the last four elements.
print(a[-1:-5:-1])
# Extract every second element from the array.
print(a[0::2])
# Reverse the array using slicing.
print(a[::-1])
# Extract elements from index 3 to the end.
print(a[2:])
# Extract elements from start to index 7.
print(a[0:7])
# Extract every third element.
print(a[0::3])

10
100
[30 40 50 60]
[10 20 30 40 50]
[100  90  80  70]
[10 30 50 70 90]
[100  90  80  70  60  50  40  30  20  10]
[ 30  40  50  60  70  80  90 100]
[10 20 30 40 50 60 70]
[ 10  40  70 100]


Two dimensional

In [31]:
a = np.array([
[1,2,3,4],
[5,6,7,8],
[9,10,11,12],
[13,14,15,16]
])
#access the element 6
print(a[1][1])
# Access element 15.
print(a[3][2])
# # Extract the first row.
print(a[0])
# # Extract the third column.
print(a[:,[2]])
# # Extract the last row.
print(a[-1])
# # Extract the first two rows.
print(a[:2,:])
# # Extract the middle 2×2 matrix.
print(a[1:3,1:3])
# # Extract all rows but only first two columns.
print(a[:,:2])
# Extract last two rows and last two columns.
print(a[2:,2:])
# # Extract every second row.
print(a[0::2])

6
15
[1 2 3 4]
[[ 3]
 [ 7]
 [11]
 [15]]
[13 14 15 16]
[[1 2 3 4]
 [5 6 7 8]]
[[ 6  7]
 [10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[11 12]
 [15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


Three Dimensional

In [50]:
a = np.array([
[
[1,2,3],
[4,5,6]
],
[
[7,8,9],
[10,11,12]
]
])
# Access element 1.
print(a[0][1][0])
# Access element 8.
print(a[1][0][1])
# Access element 12.
print(a[1][1][2])
# Extract the first 2D matrix.
print(a[0])
# Extract the second 2D matrix.
print(a[1])
# Extract the first row of the second matrix.
print(a[1][0])
# Extract all matrices but only first row.
print(a[ : ,0, : ])
# Extract all matrices but last column.
print(a[: ,: ,-1])
# Extract the column containing values [2,5].
print(a[0][:,1])
# Extract all elements from the second matrix except the first column.
print(a[1][:, 1:])

4
8
12
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[7 8 9]
[[1 2 3]
 [7 8 9]]
[[ 3  6]
 [ 9 12]]
[2 5]
[[ 8  9]
 [11 12]]
