Boolean indexing means selecting elements based on a condition.

In [2]:
import numpy as np

a = np.array([12, 5, 18, 7, 20, 3, 25, 10])
b = np.array([
    [1, 12, 3],
    [14, 5, 16],
    [7, 18, 9]
])

In [5]:
# Extract all elements from a greater than 10.
print(a[a>10])
# Extract all elements from a that are divisible by 5.
print(a[a%5==0])
# Replace all elements in a less than 10 with 0.
a[a<10]=0
print(a)
# From b, extract only the elements greater than 10.
print(b[b>10])
# From b, replace all odd numbers with -1.
b[b%2!=0]=-1
print(b)
# Extract numbers greater than row mean
print(b[b>np.mean(b, axis=1)])


[12 18 20 25]
[ 0  0 20  0 25 10]
[12  0 18  0 20  0 25 10]
[12 14 16 18]
[[-1 12 -1]
 [14 -1 16]
 [-1 18 -1]]
[12 14 16 18]


In [7]:
import numpy as np

a = np.array([
[
[1,2,3],
[4,5,6]
],
[
[7,8,9],
[10,11,12]
]
])
# Keep Shape Using np.where()
np.where(a > 5, a, 0)
#mean per matrix
mean = np.mean(a, axis=(1,2), keepdims=True)
a[a > mean]

array([ 4,  5,  6, 10, 11, 12])