In [1]:
import numpy as np
a = np.array([10,20,30,40,50,60,70,80,90])


In [ ]:
print(a[[0,3,5]])
# Extract elements at indices [2,4,6,8]
print(a[[2,4,6,8]])
# Extract elements using negative indices [-1,-3,-5]
print(a[[-1,-3,-5]])
# Select elements [20,50,80] using fancy indexing.
print(a[[1,4,7]])
# Extract the first, middle, and last element.
print(a[[1,np.size(a)//2,-1]])
# Create a new array using indices [1,1,1,4,4,7]
new_a=np.array(a[[1,1,1,4,4,7]])
print(new_a)
# Extract every second element using fancy indexing.
a = np.array([10,20,30,40,50,60,70,80])
indices = np.arange(0, len(a), 2)
result = a[indices]
print(result)

[10 40 60]
[30 50 70 90]
[90 70 50]
[20 50 80]
[20 50 90]
[20 20 20 50 50 80]


2D arrays

In [32]:
b = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])
# Extract elements [1,5,9] using fancy indexing.
result = b[[0,1,2], [0,1,2]]
print(result)
# Extract elements [3,4,8].
print(b[[0,1,2],[2,0,1]])
# Extract the entire first row using fancy indexing.
print(b[[0],[0,1,2]])
# Extract the first and third rows together.
print(b[[0,2]])
# Extract second column values using fancy indexing.
print(b[[0,1,2],[1]])

[1 5 9]
[3 4 8]
[1 2 3]
[[1 2 3]
 [7 8 9]]
[2 5 8]
