Scalar operations

In [1]:
import numpy as np

In [2]:
d=np.array([1,2,3,4,5])
print(d+1)
print(d-1)
print(d*1)
print(d//1)
print(d/1)
print(d%2)

[2 3 4 5 6]
[0 1 2 3 4]
[1 2 3 4 5]
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 0 1 0 1]


Relational Operators

In [3]:
#return true and false based on conditions
d=np.array([1,2,3,4,5])
print(d>1)
print(d<1)
print(d!=1)
print(d<=1)
print(d>=1)
print(d==1)

[False  True  True  True  True]
[False False False False False]
[False  True  True  True  True]
[ True False False False False]
[ True  True  True  True  True]
[ True False False False False]


Vector operations

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
print("Sum",a+b)
print("Mul",a-b)
print("Addition",a*b)
print("Subtraction",a/b)


Sum [ 4  6  8 10 12]
Mul [-2 -2 -2 -2 -2]
Addition [ 3  8 15 24 35]
Subtraction [0.33333333 0.5        0.6        0.66666667 0.71428571]
