In [10]:
import numpy as np
#all operations are element wise
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,2))
print(np.abs(a))
print(np.mod(a,b))
print(np.exp(a))
print(np.log10(a))
print(np.sqrt(a))

[ 6  8 10 12 14]
[-4 -4 -4 -4 -4]
[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]
[ 1  4  9 16 25]
[1 2 3 4 5]
[1 2 3 4 5]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [12]:
import numpy as np

a=np.array([1,2,3,4,5])

print("Mean:",np.mean(a))
print("Median:",np.median(a))
print("Std:",np.std(a))
print("Variance:",np.var(a))
print("Min:",np.min(a))
print("Max:",np.max(a))
print("Sum:",np.sum(a))
print("Argmin:",np.argmin(a)) #index of min
print("Argmax:",np.argmax(a)) #index of max
print("Percentile:",np.percentile(a,50))
print("cumsum:", np.cumsum(a))
print("cumprod:", np.cumprod(a)) #nan propagates
print("nancumsum:", np.nancumsum(b)) 
print("nancumprod:", np.nancumprod(b)) #nan ignores

Mean: 3.0
Median: 3.0
Std: 1.4142135623730951
Variance: 2.0
Min: 1
Max: 5
Sum: 15
Argmin: 0
Argmax: 4
Percentile: 3.0
cumsum: [ 1  3  6 10 15]
cumprod: [  1   2   6  24 120]
nancumsum: [ 5 11 18 26 35]
nancumprod: [    5    30   210  1680 15120]
