Broadcasting Rules

1. Compare shapes from right to left.
2. Dimensions must either:
   - be equal, OR
   - one of them must be 1.
3. If dimension is 1, it expands to match the other dimension.
4. If neither dimension is 1 and they are not equal → broadcasting fails.

Example:
(3,1) and (1,3) → (3,3)

In [3]:
import numpy as np
a = np.array([[1],
              [2],
              [3]])      # shape (3,1) then (3,3)

b = np.array([10,20,30]) # shape (3,) ->(3,1) ->(3,3)
print(a+b) 

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [4]:
import numpy as np
a = np.array([1,2,3]) #(3,)
b = 5 

print( a + b)
print() #[1+5 ,2+5, 3+5]

a1 = np.arange(6).reshape(2,3)  # (2,3)
b1 = np.array([10,20,30])       # (,3) -->> (1,3) --->>(2,3)
print(a1+b1)
print()

a2 = np.arange(6).reshape(2,3)
b2 = np.array([[10],
               [20]])  # (2,1) -->> (2,3)
print(a2+b2)
print()

A = np.ones((3,4))
B = np.array([10,20,30,40])

print( A + B)

[6 7 8]

[[10 21 32]
 [13 24 35]]

[[10 11 12]
 [23 24 25]]

[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]


In [5]:
a3 = np.arange(12).reshape(4,3)
b3 = np.array([1,2,3]) # (,3) -->> (1,3) -->>> (4,3)

print(a3 + b3 )
print()

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]



In [6]:
a5 = np.arange(12).reshape(3,4)  # (3,4)
b5 = np.arange(3) # (,3) -->> (1,3) -->> ( 3, 3 ) shapes didnt match so won't broadcast 
#                  we can only increament 1
print(a5)
print("\n", b5)

print( a5 + b5 )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [7]:
a7 = np.arange(12).reshape(4,3)  
b7 = np.arange(12).reshape(3,4)  # there is no one to increment and match shape in both

a7 - b7

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 