In [2]:
import numpy as np

In [6]:
# Q-1 Create a null vector of size 10 but the fifth value which is 1.
null=np.zeros((2,5))
print(null)
null[0][4]=1
print(null)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.
a=int(input("Enter the  number of rows: "))
b=int(input("Enter the number of columns: "))
c=np.random.randint((a,b))
print(c)

[2 2]


In [11]:
# Q-3 Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.
# Eg.-

# [[1,1,1,1],
# [1,0,0,1],
# [1,0,0,1],
# [1,1,1,1]]

a=int(input("Enter the  number of rows: "))
b=int(input("Enter the number of columns: "))
c=np.full((a,b),0)
c[[0,-1]]=1
c[: ,[0,-1]]=1
print(c)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [19]:
# Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.
a=np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
# Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it. No
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.
import numpy as np
a = np.arange(5)
a = np.repeat(a.reshape(1,5), 5, axis=0)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#second way   
a = np.tile(np.arange(5), (5,1)) #(rep, axis)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
# Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, 
# and coordinates of a point as array is given. Create an array of distance of each point in the random 
# vectros from the given point. Distance array should be interger type.
# point = np.array([2,3]) 


In [40]:
# Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import numpy as np
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


In [39]:
# Q-9: Arrays
# You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.
# Input Format:
# A single line of input containing space separated numbers.
# Output Format:
# Print the reverse NumPy array with type float.
# Example 1:
# Input:
# 1 2 3 4 -8 -10
# Output:
# [-10.  -8.   4.   3.   2.   1.]

import numpy as np

a = "1 2 3 4 -8 -10".split()

arr = np.array(a, float)

print(arr[::-1])

[-10.  -8.   4.   3.   2.   1.]


In [38]:
# Q-10: Elements count
# Count the number of elements of a numpy array.
# Example 1:
# Input:
# np.array([])
# Output:
# elements_count :  0
# Example 2:
# Input:
# np.array([1, 2])
# Output:
# elements_count :  2
a=np.array([1, 2])
print("Element_count",a.size)

Element_count 2


In [3]:
# Q-11: Softmax function
# Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

# σ(z⃗ )i=ezi∑Kj=iezj 

# https://en.wikipedia.org/wiki/Softmax_function

# Example 1
# Input:
# [86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
# Output:
# [2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
#        5.05514197e-22, 1.50974911e-22]
# Example 2:
# Input:
# [33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
# Output:
# [4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
#        1.39571531e-10, 9.99896577e-01]
import numpy as np
def softmax(arr):
    if not isinstance(arr, np.ndarray):
        raise TypeError("Input must be a NumPy array")
    if arr.ndim!=1:
        raise ValueError("Input must be a 1D NumPy array")
    exp_values = np.exp(arr)
    softmax_values = exp_values / np.sum(exp_values)
    
    return softmax_values

a = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])
print(softmax(a))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


<!-- Q-12: Vertical stack
Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

Example 1:

Input:

a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
Output:

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Example 2:

Input:

a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
Output:

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] -->

In [ ]:
def vertstacking(*args): #accepts the tuple of arrays so check individual array

    # check if at least one array is given
    if len(args) == 0:
        raise ValueError("At least one NumPy array must be provided")
    for arr in args:
        if not isinstance(arr, np.ndarray):
            raise TypeError("Input must be a NumPy array")
    resultant=np.vstack(args)
    return resultant

a = np.array([[0,1,2,3,4],
              [5,6,7,8,9]])

b = np.array([[1,1,1,1,1],
              [1,1,1,1,1]])

print(vertstacking(a,b))


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [28]:
# Q-13: Dates
# Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, 
# otherwise raise error. The date format should be like this only: 2022-12-6. 
# The end date should be included and for simplicity, choose dates from a same year.

# Example 1:

# Input:

# date_array(start = '2020-09-15', end = '2020-09-25')
# Output:

# ['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
#  '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
#  '2020-09-23', '2020-09-24', '2020-09-25']
# Example 2:

# Input:

# date_array(start = '2022-12-01', end = '2022-12-06')
# Output:

# ['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
# Example 3:

# Input:

# date_array(start = '2020-11-25', end = '2020-11-30')
# Output:

# ['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
#  '2020-11-29', '2020-11-30']

import numpy as np

def date_array(start, end):

    # type checking
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both inputs must be strings")

    start_date = np.datetime64(start)
    end_date = np.datetime64(end)

    # include end date
    dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'))

    return dates

print(date_array('2020-09-15', '2020-09-25'))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


In [10]:
# Q-14: Subtract the mean of each row from a matrix.
a = np.array([[0,1,2,3,4]])
mean=np.mean(a, axis=1)
print(a-mean)

[[-2. -1.  0.  1.  2.]]


In [15]:
# Q-15: Swap column-1 of array with column-2 in the array.
# a = np.array([[0,1,2,3,4]])
# swap=np.swapaxes(a, a[0], a[1])
# print(swap) #swap axes id used to swap dimensions not the column
import numpy as np

a = np.array([[0,1,2,3,4]])

# swap column 1 and column 2
a[:, [1,2]] = a[:, [2,1]]

print(a)


[[0 2 1 3 4]]


In [17]:
# Q-16: Replace odd elements in arrays with -1.

a = np.array([0,1,2,3,4])
a[a%2!=0]=-1
print(a)

[ 0 -1  2 -1  4]


In [ ]:
# Q-17: Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
# a=np.array([6,3,1,5,8])
# b=np.array([3,2,1,7,2])

# Result-> [6 3 1 7 8]

#element wise comparison
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
np.maximum(a,b) #max is used for max of an array and maximum for element wise comparison


array([6, 3, 1, 7, 8])

In [26]:
# Q-18 Answer below asked questions on given array:
# Fetch Every alternate column of the array
# Normalise the given array
# https://en.wikipedia.org/wiki/Normalization_(statistics)

# There are different form of normalisation for this question use below formula.

# Xnormalized=X−XminXmax−Xmin 

# arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
# Given
# arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
# arr1
import numpy as np

# given array
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8,5)

print("Original Array:\n", arr1)

#Fetch every alternate column
alternate_columns = arr1[:, ::2]
print("\nAlternate Columns:\n", alternate_columns)

#Normalize the array
xmin = np.min(arr1)
xmax = np.max(arr1)

normalized_array = (arr1 - xmin) / (xmax - xmin)

print("\nNormalized Array:\n", normalized_array)


Original Array:
 [[6873 1031 4320 2375 5769]
 [ 641 2833 3259 3623 2549]
 [8364 5802 5545 3386 7500]
 [8365 2305 1154 8878 4038]
 [4055 9053  619 6613 3084]
 [5468 1455 7355 5893 1960]
 [ 945 1316 4715 1161 4608]
 [9057 5996 4206 7867 5216]]

Alternate Columns:
 [[6873 4320 5769]
 [ 641 3259 2549]
 [8364 5545 7500]
 [8365 1154 4038]
 [4055  619 3084]
 [5468 7355 1960]
 [ 945 4715 4608]
 [9057 4206 5216]]

Normalized Array:
 [[0.74117089 0.04882674 0.43861105 0.20810619 0.6103342 ]
 [0.00260725 0.26238445 0.31287035 0.35600853 0.22872719]
 [0.91787153 0.61424508 0.58378763 0.32792131 0.8154776 ]
 [0.91799005 0.19981038 0.06340365 0.97878644 0.4051908 ]
 [0.4072055  0.99952595 0.         0.7103579  0.29213084]
 [0.57466224 0.09907561 0.79829343 0.62502963 0.15892392]
 [0.03863475 0.08260251 0.48542309 0.06423323 0.47274236]
 [1.         0.63723631 0.42510073 0.85897132 0.54479735]]


In [36]:
# Q-19: Write a function which will accept 2 arguments.
# First: A 1D numpy array arr

# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be

import numpy as np

def find_value(arr, n):
    if n > len(arr):
        print("n should be <=", len(arr))
        return None
    
    arr_sorted = np.sort(arr)[::-1]   # sort descending
    return arr_sorted[n-1]


a = np.array([12,34,40,7,1,0])
result = find_value(a,3)

print(result)

12


In [ ]:
# Q-20: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
import numpy as np
a = np.array([1,2,3])
part1 = np.repeat(a,3)
part2 = np.tile(a,3)
result = np.concatenate((part1, part2))
print(result)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])