In [2]:
import numpy as np

In [15]:
# i. Sort this matrix. np.sort()
# ii. Sort this matrix based on values in 2nd column.
# iii. Sort this matrix based on max value in each row.
# iv. Sort based on elements value.
import numpy as np

a = np.random.randint(0,100,12).reshape(3,4)

print("Original Matrix:\n",a)

# i
print("\nRow wise sorted:\n",np.sort(a))

# ii
print("\nSorted by 2nd column:\n",a[a[:,1].argsort()])

# iii
print("\nSorted by row max:\n",a[a.max(axis=1).argsort()])

# iv
print("\nAll elements sorted:\n",np.sort(a,axis=None))

Original Matrix:
 [[25 19 58 44]
 [56 67 14 15]
 [95 96 80 31]]

Row wise sorted:
 [[19 25 44 58]
 [14 15 56 67]
 [31 80 95 96]]

Sorted by 2nd column:
 [[25 19 58 44]
 [56 67 14 15]
 [95 96 80 31]]

Sorted by row max:
 [[25 19 58 44]
 [56 67 14 15]
 [95 96 80 31]]

All elements sorted:
 [14 15 19 25 31 44 56 58 67 80 95 96]


In [30]:
import numpy as np

a = np.random.randint(0, 75, 20).reshape(5, 4)
print("Original array:\n", a)

# i. Add marks for one extra subject to all existing students
extra_subject = np.array([[23],
                          [24],
                          [25],
                          [26],
                          [12]])
a = np.hstack((a, extra_subject))
print("\nAfter adding extra subject:\n", a)

# ii. Add two new students (now each must have 5 subject marks)
new_students = np.array([[34, 45, 56, 67, 21],
                         [11, 22, 33, 44, 55]])
a = np.vstack((a, new_students))
print("\nAfter adding two new students:\n", a)

# iii. Add total marks column
total = np.sum(a, axis=1).reshape(-1, 1)
a = np.hstack((a, total))
print("\nAfter adding total marks column:\n", a)

# iv. Sort by total marks in descending order and show top 2 rows
sorted_array = a[a[:, -1].argsort()[::-1]]
top2 = sorted_array[:2]
print("\nTop 2 students based on total marks:\n", top2)

Original array:
 [[41  2 41 40]
 [57 44 50 67]
 [ 0 73 11 22]
 [62  0  1 64]
 [37  7 23 40]]

After adding extra subject:
 [[41  2 41 40 23]
 [57 44 50 67 24]
 [ 0 73 11 22 25]
 [62  0  1 64 26]
 [37  7 23 40 12]]

After adding two new students:
 [[41  2 41 40 23]
 [57 44 50 67 24]
 [ 0 73 11 22 25]
 [62  0  1 64 26]
 [37  7 23 40 12]
 [34 45 56 67 21]
 [11 22 33 44 55]]

After adding total marks column:
 [[ 41   2  41  40  23 147]
 [ 57  44  50  67  24 242]
 [  0  73  11  22  25 131]
 [ 62   0   1  64  26 153]
 [ 37   7  23  40  12 119]
 [ 34  45  56  67  21 223]
 [ 11  22  33  44  55 165]]

Top 2 students based on total marks:
 [[ 57  44  50  67  24 242]
 [ 34  45  56  67  21 223]]


In [31]:
# Q-3
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

# Unique rows
row_unique = np.unique(arr, axis=0)
print("Row Wise:\n", row_unique)

# Unique columns
col_unique = np.unique(arr, axis=1)
print("\nCol Wise:\n", col_unique)

Row Wise:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise:
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


In [32]:
# Q-4
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Original:\n", arr)

# Flip both axes
flipped = np.flip(arr)
print("\nFlipped along both axes:\n", flipped)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped along both axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [33]:
# Q-6
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

flat = np.hstack((arr1, arr2, arr3))
print(flat)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
# Q-7
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

print("Original array:\n", arr)

min_val = arr.min()
max_val = arr.max()

print("\nMinimum value:", min_val)
print("Maximum value:", max_val)

# Remove min and max
filtered = arr[(arr != min_val) & (arr != max_val)]
print("\nArray after removing min and max:\n", filtered)

Original array:
 [[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]

Minimum value: 103
Maximum value: 998

Array after removing min and max:
 [448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 

In [35]:
# Q-8
np.random.seed(42)
arr = np.random.randint(100, 701, 20)

print("Original array:\n", arr)

# Limit values between 100 and 200
clipped = np.clip(arr, 100, 200)
print("\nClipped array:\n", clipped)

# Sort the array
sorted_arr = np.sort(clipped)
print("\nSorted array:\n", sorted_arr)

# Cumulative sum
cumulative = np.cumsum(sorted_arr)
print("\nCumulative sum:\n", cumulative)

Original array:
 [202 535 370 206 171 120 221 566 314 430 558 187 472 199 230 408 443 591
 513 485]

Clipped array:
 [200 200 200 200 171 120 200 200 200 200 200 187 200 199 200 200 200 200
 200 200]

Sorted array:
 [120 171 187 199 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200]

Cumulative sum:
 [ 120  291  478  677  877 1077 1277 1477 1677 1877 2077 2277 2477 2677
 2877 3077 3277 3477 3677 3877]


In [ ]:
# Q-9
np.random.seed(42)
arr = np.random.rand(20)

print("Original array:\n", arr)

# Round to 3 decimal places
rounded = np.round(arr, 3)
print("\nRounded array:\n", rounded)

# 0th percentile and minimum
p0 = np.percentile(rounded, 0)
min_val = rounded.min()

# 100th percentile and maximum
p100 = np.percentile(rounded, 100)
max_val = rounded.max()

print("\n0th percentile:", p0)
print("Minimum value :", min_val)
print("Are they equal?", p0 == min_val)

print("\n100th percentile:", p100)
print("Maximum value   :", max_val)
print("Are they equal?", p100 == max_val)

# Difference between 51st and 50th percentile
p51 = np.percentile(rounded, 51)
p50 = np.percentile(rounded, 50)

print("\n51st percentile:", p51)
print("50th percentile:", p50)
print("Difference:", p51 - p50)

In [36]:
import numpy as np

arr = np.array([[1,2,3,4,5], 
                [10,-3,30,4,5], 
                [3,2,5,-4,5], 
                [9,7,3,6,5]])

X = 6

rows = np.where(arr.max(axis=1) > X)[0]

print(rows)

[1 3]


.any() → at least one True
.all() → every value must be True